/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ReconnectRouteImport } from './routes/reconnect'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminLayoutIndexRouteImport } from './routes/admin/_layout/index'
import { Route as AdminLayoutAntiTetheringRouteImport } from './routes/admin/_layout/anti-tethering'
import { Route as AdminLayoutPlansRouteImport } from './routes/admin/_layout/plans'
import { Route as AdminLayoutRoutersRouteImport } from './routes/admin/_layout/routers'
import { Route as AdminLayoutSessionsRouteImport } from './routes/admin/_layout/sessions'
import { Route as AdminLayoutSettingsRouteImport } from './routes/admin/_layout/settings'
import { Route as AdminLayoutTransactionsRouteImport } from './routes/admin/_layout/transactions'
import { Route as AdminLayoutVouchersRouteImport } from './routes/admin/_layout/vouchers'
import { Route as ApiPublicMpesaCallbackRouteImport } from './routes/api/public/mpesa/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconnectRoute = ReconnectRouteImport.update({
  id: '/reconnect',
  path: '/reconnect',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutIndexRoute = AdminLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutAntiTetheringRoute =
  AdminLayoutAntiTetheringRouteImport.update({
    id: '/anti-tethering',
    path: '/anti-tethering',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutPlansRoute = AdminLayoutPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutRoutersRoute = AdminLayoutRoutersRouteImport.update({
  id: '/routers',
  path: '/routers',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutSessionsRoute = AdminLayoutSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutSettingsRoute = AdminLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutTransactionsRoute = AdminLayoutTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutVouchersRoute = AdminLayoutVouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const ApiPublicMpesaCallbackRoute = ApiPublicMpesaCallbackRouteImport.update({
  id: '/api/public/mpesa/callback',
  path: '/api/public/mpesa/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reconnect': typeof ReconnectRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/anti-tethering': typeof AdminLayoutAntiTetheringRoute
  '/admin/plans': typeof AdminLayoutPlansRoute
  '/admin/routers': typeof AdminLayoutRoutersRoute
  '/admin/sessions': typeof AdminLayoutSessionsRoute
  '/admin/settings': typeof AdminLayoutSettingsRoute
  '/admin/transactions': typeof AdminLayoutTransactionsRoute
  '/admin/vouchers': typeof AdminLayoutVouchersRoute
  '/admin/': typeof AdminLayoutIndexRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reconnect': typeof ReconnectRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/anti-tethering': typeof AdminLayoutAntiTetheringRoute
  '/admin/plans': typeof AdminLayoutPlansRoute
  '/admin/routers': typeof AdminLayoutRoutersRoute
  '/admin/sessions': typeof AdminLayoutSessionsRoute
  '/admin/settings': typeof AdminLayoutSettingsRoute
  '/admin/transactions': typeof AdminLayoutTransactionsRoute
  '/admin/vouchers': typeof AdminLayoutVouchersRoute
  '/admin': typeof AdminLayoutIndexRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reconnect': typeof ReconnectRoute
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/_layout/anti-tethering': typeof AdminLayoutAntiTetheringRoute
  '/admin/_layout/plans': typeof AdminLayoutPlansRoute
  '/admin/_layout/routers': typeof AdminLayoutRoutersRoute
  '/admin/_layout/sessions': typeof AdminLayoutSessionsRoute
  '/admin/_layout/settings': typeof AdminLayoutSettingsRoute
  '/admin/_layout/transactions': typeof AdminLayoutTransactionsRoute
  '/admin/_layout/vouchers': typeof AdminLayoutVouchersRoute
  '/admin/_layout/': typeof AdminLayoutIndexRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reconnect'
    | '/admin'
    | '/admin/login'
    | '/admin/anti-tethering'
    | '/admin/plans'
    | '/admin/routers'
    | '/admin/sessions'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/vouchers'
    | '/admin/'
    | '/api/public/mpesa/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reconnect'
    | '/admin/login'
    | '/admin/anti-tethering'
    | '/admin/plans'
    | '/admin/routers'
    | '/admin/sessions'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/vouchers'
    | '/admin'
    | '/api/public/mpesa/callback'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/reconnect'
    | '/admin/_layout'
    | '/admin/login'
    | '/admin/_layout/anti-tethering'
    | '/admin/_layout/plans'
    | '/admin/_layout/routers'
    | '/admin/_layout/sessions'
    | '/admin/_layout/settings'
    | '/admin/_layout/transactions'
    | '/admin/_layout/vouchers'
    | '/admin/_layout/'
    | '/api/public/mpesa/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ReconnectRoute: typeof ReconnectRoute
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  ApiPublicMpesaCallbackRoute: typeof ApiPublicMpesaCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconnect': {
      id: '/reconnect'
      path: '/reconnect'
      fullPath: '/reconnect'
      preLoaderRoute: typeof ReconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout/': {
      id: '/admin/_layout/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminLayoutIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/anti-tethering': {
      id: '/admin/_layout/anti-tethering'
      path: '/anti-tethering'
      fullPath: '/admin/anti-tethering'
      preLoaderRoute: typeof AdminLayoutAntiTetheringRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/plans': {
      id: '/admin/_layout/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminLayoutPlansRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/routers': {
      id: '/admin/_layout/routers'
      path: '/routers'
      fullPath: '/admin/routers'
      preLoaderRoute: typeof AdminLayoutRoutersRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/sessions': {
      id: '/admin/_layout/sessions'
      path: '/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AdminLayoutSessionsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/settings': {
      id: '/admin/_layout/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminLayoutSettingsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/transactions': {
      id: '/admin/_layout/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminLayoutTransactionsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/vouchers': {
      id: '/admin/_layout/vouchers'
      path: '/vouchers'
      fullPath: '/admin/vouchers'
      preLoaderRoute: typeof AdminLayoutVouchersRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/api/public/mpesa/callback': {
      id: '/api/public/mpesa/callback'
      path: '/api/public/mpesa/callback'
      fullPath: '/api/public/mpesa/callback'
      preLoaderRoute: typeof ApiPublicMpesaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminLayoutRouteChildren {
  AdminLayoutAntiTetheringRoute: typeof AdminLayoutAntiTetheringRoute
  AdminLayoutPlansRoute: typeof AdminLayoutPlansRoute
  AdminLayoutRoutersRoute: typeof AdminLayoutRoutersRoute
  AdminLayoutSessionsRoute: typeof AdminLayoutSessionsRoute
  AdminLayoutSettingsRoute: typeof AdminLayoutSettingsRoute
  AdminLayoutTransactionsRoute: typeof AdminLayoutTransactionsRoute
  AdminLayoutVouchersRoute: typeof AdminLayoutVouchersRoute
  AdminLayoutIndexRoute: typeof AdminLayoutIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutAntiTetheringRoute: AdminLayoutAntiTetheringRoute,
  AdminLayoutPlansRoute: AdminLayoutPlansRoute,
  AdminLayoutRoutersRoute: AdminLayoutRoutersRoute,
  AdminLayoutSessionsRoute: AdminLayoutSessionsRoute,
  AdminLayoutSettingsRoute: AdminLayoutSettingsRoute,
  AdminLayoutTransactionsRoute: AdminLayoutTransactionsRoute,
  AdminLayoutVouchersRoute: AdminLayoutVouchersRoute,
  AdminLayoutIndexRoute: AdminLayoutIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ReconnectRoute: ReconnectRoute,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  ApiPublicMpesaCallbackRoute: ApiPublicMpesaCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
