/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ReconnectRouteImport } from './routes/reconnect'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as AdminLayoutIndexRouteImport } from './routes/admin/index'
import { Route as AdminLayoutRoutersRouteImport } from './routes/admin/routers'
import { Route as AdminLayoutPlansRouteImport } from './routes/admin/plans'
import { Route as AdminLayoutVouchersRouteImport } from './routes/admin/vouchers'
import { Route as AdminLayoutSessionsRouteImport } from './routes/admin/sessions'
import { Route as AdminLayoutTransactionsRouteImport } from './routes/admin/transactions'
import { Route as AdminLayoutAntiTetheringRouteImport } from './routes/admin/anti-tethering'
import { Route as AdminLayoutSettingsRouteImport } from './routes/admin/settings'
import { Route as ApiPublicMpesaCallbackRouteImport } from './routes/api/public/mpesa/callback'

// Flat routes (no layout nesting)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)

const ReconnectRoute = ReconnectRouteImport.update({
  id: '/reconnect',
  path: '/reconnect',
  getParentRoute: () => rootRouteImport,
} as any)

const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

// Admin layout (parent for all /admin/* except /admin/login)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)

// Admin layout children
const AdminLayoutIndexRoute = AdminLayoutIndexRouteImport.update({
  id: '/admin/_layout/',
  path: '/',
  getParentRoute: () => AdminLayoutRoute,
} as any)

const AdminLayoutRoutersRoute = AdminLayoutRoutersRouteImport.update({
  id: '/admin/_layout/routers',
  path: '/routers',
  getParentRoute: () => AdminLayoutRoute,
} as any)

const AdminLayoutPlansRoute = AdminLayoutPlansRouteImport.update({
  id: '/admin/_layout/plans',
  path: '/plans',
  getParentRoute: () => AdminLayoutRoute,
} as any)

const AdminLayoutVouchersRoute = AdminLayoutVouchersRouteImport.update({
  id: '/admin/_layout/vouchers',
  path: '/vouchers',
  getParentRoute: () => AdminLayoutRoute,
} as any)

const AdminLayoutSessionsRoute = AdminLayoutSessionsRouteImport.update({
  id: '/admin/_layout/sessions',
  path: '/sessions',
  getParentRoute: () => AdminLayoutRoute,
} as any)

const AdminLayoutTransactionsRoute = AdminLayoutTransactionsRouteImport.update({
  id: '/admin/_layout/transactions',
  path: '/transactions',
  getParentRoute: () => AdminLayoutRoute,
} as any)

const AdminLayoutAntiTetheringRoute = AdminLayoutAntiTetheringRouteImport.update({
  id: '/admin/_layout/anti-tethering',
  path: '/anti-tethering',
  getParentRoute: () => AdminLayoutRoute,
} as any)

const ApiPublicMpesaCallbackRoute = ApiPublicMpesaCallbackRouteImport.update({
  id: '/api/public/mpesa/callback',
  path: '/api/public/mpesa/callback',
  getParentRoute: () => rootRouteImport,
} as any)

// Wire up the admin layout children
const AdminLayoutSettingsRoute = AdminLayoutSettingsRouteImport.update({
  id: '/admin/_layout/settings',
  path: '/settings',
  getParentRoute: () => AdminLayoutRoute,
} as any)

// Wire up the admin layout children
const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren([
  AdminLayoutIndexRoute,
  AdminLayoutRoutersRoute,
  AdminLayoutPlansRoute,
  AdminLayoutVouchersRoute,
  AdminLayoutSessionsRoute,
  AdminLayoutTransactionsRoute,
  AdminLayoutAntiTetheringRoute,
  AdminLayoutSettingsRoute,
])

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reconnect': typeof ReconnectRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/admin/': typeof AdminLayoutIndexRoute
  '/admin/routers': typeof AdminLayoutRoutersRoute
  '/admin/plans': typeof AdminLayoutPlansRoute
  '/admin/vouchers': typeof AdminLayoutVouchersRoute
  '/admin/sessions': typeof AdminLayoutSessionsRoute
  '/admin/transactions': typeof AdminLayoutTransactionsRoute
  '/admin/anti-tethering': typeof AdminLayoutAntiTetheringRoute
  '/admin/settings': typeof AdminLayoutSettingsRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reconnect': typeof ReconnectRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminLayoutIndexRoute
  '/admin/routers': typeof AdminLayoutRoutersRoute
  '/admin/plans': typeof AdminLayoutPlansRoute
  '/admin/vouchers': typeof AdminLayoutVouchersRoute
  '/admin/sessions': typeof AdminLayoutSessionsRoute
  '/admin/transactions': typeof AdminLayoutTransactionsRoute
  '/admin/anti-tethering': typeof AdminLayoutAntiTetheringRoute
  '/admin/settings': typeof AdminLayoutSettingsRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
}

export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reconnect': typeof ReconnectRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/admin/_layout/': typeof AdminLayoutIndexRoute
  '/admin/_layout/routers': typeof AdminLayoutRoutersRoute
  '/admin/_layout/plans': typeof AdminLayoutPlansRoute
  '/admin/_layout/vouchers': typeof AdminLayoutVouchersRoute
  '/admin/_layout/sessions': typeof AdminLayoutSessionsRoute
  '/admin/_layout/transactions': typeof AdminLayoutTransactionsRoute
  '/admin/_layout/anti-tethering': typeof AdminLayoutAntiTetheringRoute
  '/admin/_layout/settings': typeof AdminLayoutSettingsRoute
  '/api/public/mpesa/callback': typeof ApiPublicMpesaCallbackRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reconnect'
    | '/admin/login'
    | '/admin'
    | '/admin/'
    | '/admin/routers'
    | '/admin/plans'
    | '/admin/vouchers'
    | '/admin/sessions'
    | '/admin/transactions'
    | '/admin/anti-tethering'
    | '/admin/settings'
    | '/api/public/mpesa/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reconnect'
    | '/admin/login'
    | '/admin'
    | '/admin/routers'
    | '/admin/plans'
    | '/admin/vouchers'
    | '/admin/sessions'
    | '/admin/transactions'
    | '/admin/anti-tethering'
    | '/admin/settings'
    | '/api/public/mpesa/callback'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/reconnect'
    | '/admin/login'
    | '/admin/_layout'
    | '/admin/_layout/'
    | '/admin/_layout/routers'
    | '/admin/_layout/plans'
    | '/admin/_layout/vouchers'
    | '/admin/_layout/sessions'
    | '/admin/_layout/transactions'
    | '/admin/_layout/anti-tethering'
    | '/admin/_layout/settings'
    | '/api/public/mpesa/callback'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ReconnectRoute: typeof ReconnectRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  ApiPublicMpesaCallbackRoute: typeof ApiPublicMpesaCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconnect': {
      id: '/reconnect'
      path: '/reconnect'
      fullPath: '/reconnect'
      preLoaderRoute: typeof ReconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout/': {
      id: '/admin/_layout/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminLayoutIndexRouteImport
      parentRoute: typeof AdminLayoutRouteImport
    }
    '/admin/_layout/routers': {
      id: '/admin/_layout/routers'
      path: '/routers'
      fullPath: '/admin/routers'
      preLoaderRoute: typeof AdminLayoutRoutersRouteImport
      parentRoute: typeof AdminLayoutRouteImport
    }
    '/admin/_layout/plans': {
      id: '/admin/_layout/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminLayoutPlansRouteImport
      parentRoute: typeof AdminLayoutRouteImport
    }
    '/admin/_layout/vouchers': {
      id: '/admin/_layout/vouchers'
      path: '/vouchers'
      fullPath: '/admin/vouchers'
      preLoaderRoute: typeof AdminLayoutVouchersRouteImport
      parentRoute: typeof AdminLayoutRouteImport
    }
    '/admin/_layout/sessions': {
      id: '/admin/_layout/sessions'
      path: '/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AdminLayoutSessionsRouteImport
      parentRoute: typeof AdminLayoutRouteImport
    }
    '/admin/_layout/transactions': {
      id: '/admin/_layout/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminLayoutTransactionsRouteImport
      parentRoute: typeof AdminLayoutRouteImport
    }
    '/admin/_layout/anti-tethering': {
      id: '/admin/_layout/anti-tethering'
      path: '/anti-tethering'
      fullPath: '/admin/anti-tethering'
      preLoaderRoute: typeof AdminLayoutAntiTetheringRouteImport
      parentRoute: typeof AdminLayoutRouteImport
    }
    '/admin/_layout/settings': {
      id: '/admin/_layout/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminLayoutSettingsRouteImport
      parentRoute: typeof AdminLayoutRouteImport
    }
    '/api/public/mpesa/callback': {
      id: '/api/public/mpesa/callback'
      path: '/api/public/mpesa/callback'
      fullPath: '/api/public/mpesa/callback'
      preLoaderRoute: typeof ApiPublicMpesaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ReconnectRoute: ReconnectRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  ApiPublicMpesaCallbackRoute: ApiPublicMpesaCallbackRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
